### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by DieterHolvoet** [caiguanhao/yt#1]
## Error message
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/dieter/.config/yarn/global/node_modules/yt/api.js:92:21)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

## Steps to reproduce
1. Install the command globally using Yarn 1.1.0
2. 'Copy as cURL' a instructed and execute `yt`

## Remarks
- After executing `yt` the file `~/.config/yt/cookie.json` contains 4 values: `LOGIN_INFO`, `SID`, `HSID`, `SSID`

**Comment by caiguanhao** [comment]
It worked 3 years ago. Every time YouTube updates its subscriptions page, it might break this tool.
